#!/usr/bin/env python3

import cgi, cgitb, codecs, hashlib, shutil, sys
from icalendar import Calendar

DOMAIN = 'chris.boyle.name'

sys.stdout = codecs.getwriter('utf-8')(sys.stdout.detach())
cgitb.enable()

form = cgi.FieldStorage()
ics = None
if 'ics' in form and form['ics'].file:
    ics = form['ics'].file.read()
elif len(sys.argv) > 1:
    with open(sys.argv[1], 'r') as f:
        ics = f.read()

if ics:
    try:
        cal = Calendar.from_ical(ics)
    except Exception as ex:
        raise ValueError("Couldn't load that as an ical file") from ex
    for event in cal.walk('VEVENT'):
        dtstart = event.get('DTSTART', None)
        summary = event.get('SUMMARY', None)
        if dtstart is None or summary is None:
            raise ValueError('event lacked summary and/or dtstart: ' + str(event))
        to_hash = str(dtstart.to_ical()) + '/' + str(summary.to_ical())
        event['UID'] = hashlib.sha256(to_hash.encode('utf-8')).hexdigest() + '@' + DOMAIN
        if 'public' in form or '--public' in sys.argv:
            event['CLASS'] = 'PUBLIC'
        paras = event['DESCRIPTION'].split('\n\n', 2)
        if len(paras) == 3 and paras[0] == 'Item in personal schedule':
            # Grenadine special case
            event['LOCATION'] = paras[1]
            event['DESCRIPTION'] = paras[2]
    if 'ics' in form:
        print('Content-Type: text/calendar; charset=utf-8\nContent-Disposition: attachment; filename="fixed_' + form['ics'].filename + '"\n')
    print(cal.to_ical().decode('utf-8'), end='')

else:
    with open('ics-fix-uids-info.html', 'r') as info:
        print('Content-Type: text/html; charset=utf-8\n')
        shutil.copyfileobj(info, sys.stdout)
