#!/usr/bin/env python3

import cgi, cgitb, codecs, hashlib, json, re, shutil, sys
from html import escape
from icalendar import Calendar, vCalAddress, vText

DOMAIN = 'chris.boyle.name'

sys.stdout = codecs.getwriter('utf-8')(sys.stdout.detach())
cgitb.enable()

form = cgi.FieldStorage()
ics = None
if 'ics' in form and form['ics'].file:
    ics = form['ics'].file.read()
elif len(sys.argv) > 1:
    with open(sys.argv[1], 'r') as f:
        ics = f.read()

nw_extra = {}
try:
    with open('nw_extra.json', 'r') as f:
        nw_extra = json.load(f)
except:
    pass

if ics:
    try:
        cal = Calendar.from_ical(ics)
    except Exception as ex:
        raise ValueError("Couldn't load that as an ical file") from ex
    for event in cal.walk('VEVENT'):
        dtstart = event.get('DTSTART', None)
        summary = event.get('SUMMARY', None)
        if dtstart is None or summary is None:
            raise ValueError('event lacked summary and/or dtstart: ' + str(event))
        to_hash = str(dtstart.to_ical()) + '/' + str(summary.to_ical())
        event['UID'] = hashlib.sha256(to_hash.encode('utf-8')).hexdigest() + '@' + DOMAIN
        if 'public' in form or '--public' in sys.argv:
            event['CLASS'] = 'PUBLIC'
        paras = event['DESCRIPTION'].split('\n\n', 2)
        if len(paras) == 3 and paras[0] == 'Item in personal schedule':
            # Grenadine special case
            event['LOCATION'] = paras[1]
            event['DESCRIPTION'] = paras[2]
        html = '<br/><br/>'.join(map(lambda p: escape(p.strip()), filter(lambda x: x, event['DESCRIPTION'].split('\n'))))
        extra = nw_extra.get(summary.split(' | ', 1)[0].strip())
        if extra:
            event['DESCRIPTION'] += ''.join(map(lambda e: '\n\n' + e['url'], extra))
            html += '<br/><br/>' + '<br/><br/>'.join(map(lambda e: '<a href="' + e['url'] + '">Event info</a>', extra))
            if len(extra) == 1 and extra[0]['speakers']:
                event['DESCRIPTION'] += ''.join(map(lambda s: '\n\n' + s['name'] + (' (moderator)' if s['moderator'] else '') + '\n' + s['url'], extra[0]['speakers']))
                html += '<br/><br/><ul>' + '\n'.join(map(lambda s: '<li><a href="' + s['url'] + '">' + s['name'] + (' (moderator)' if s['moderator'] else '') + '</a></li>', extra[0]['speakers'])) + '</ul>'
                #for s in extra[0]['speakers']:
                #    att = vCalAddress(re.sub(r'[^\w]+', '_', s['name']) + '@address-unknown.invalid')
                #    att.params['CN'] = s['name']
                #    att.params['DIR'] = s['url']
                #    att.params['PARTSTAT'] = 'ACCEPTED'
                #    if s['moderator']:
                #        att.params['ROLE'] = 'CHAIR'
                #    event.add('attendee', att, encode=0)
        html = '<!DOCTYPE html><html><body>' + html + '</body></html>'
        if 'forcehtml' in form or '--forcehtml' in sys.argv:
            event['DESCRIPTION'] = html
        else:
            htmlDesc = vText(html)
            htmlDesc.params['fmttype'] = 'text/html'
            event.add('x-alt-desc', htmlDesc)
    if 'ics' in form:
        print('Content-Type: text/calendar; charset=utf-8\nContent-Disposition: attachment; filename="fixed_' + form['ics'].filename + '"\n')
    print(cal.to_ical().decode('utf-8'), end='')

else:
    with open('ics-fix-uids-info.html', 'r') as info:
        print('Content-Type: text/html; charset=utf-8\n')
        shutil.copyfileobj(info, sys.stdout)
